### ISSUE TITLE
Weapon Leaderboard with all factions

### ISSUE THREAD

**Issue by Corb4n** [Lampjaw/Voidwell.com#1]
Hi. 
I'm looking for a stats comparison for a weapon including all factions.

**Comment by Lampjaw** [comment]
You mean like the weapons leaderboard page for NS weapons? https://voidwell.com/ps2/item/316/leaderboard

**Comment by Corb4n** [comment]
> You mean like the weapons leaderboard page for NS weapons? https://voidwell.com/ps2/item/316/leaderboard

Yep. : )
The Tankbuster for example is playable by all factions. I just realized it probably will be only the NS and some vehicle weapons.

**Comment by Lampjaw** [comment]
Oh, I see what you mean, yea unfortunately since vehicle weapons all have different IDs even if every faction has a copy of that weapon there's no way for the system to know that they're supposed to be the same without me manually making a list.

**Comment by Corb4n** [comment]
> Oh, I see what you mean, yea unfortunately since vehicle weapons all have different IDs even if every faction has a copy of that weapon there's no way for the system to know that they're supposed to be the same without me manually making a list.

http://stats.dasanfall.com/ps2/item_leaderboard.php?query=5216
