### ISSUE TITLE
"Unknown Error" after 10 seconds of loading

### ISSUE THREAD

**Issue by ghost** [Lampjaw/Voidwell.com#5]
Hi there,

It's been roughly a week since the website stopped working correctly.
The "Unknown Error" message appears on every page I try to visit.

![1](https://github.com/voidwell/Voidwell.com/assets/20138277/edbee713-b138-413f-ba75-40a2112dd787)

**Comment by Talthos** [comment]
Happening with me as well. Tested with the Firefox browser, Google Chrome, and Microsoft Edge.

**Comment by ghost** [comment]
It's working again now, so I guess I'll close the issue.
